### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by Micke60** [mplutka/tm-bt-led#1]
Amazing for this mod. 

I am unable to install the mod.
Should I switch the BT on or turn it off. Or perhaps I forgot to do something important.
Thanks

Micke

![Install](https://user-images.githubusercontent.com/79248779/108325005-e851b980-71c8-11eb-92fe-52f2cb7b3999.jpg)

**Comment by mplutka** [comment]
The command is `non install`

**Comment by Micke60** [comment]
![install](https://user-images.githubusercontent.com/79248779/108422745-38676500-7237-11eb-87ee-f8fad2da3d3e.jpg)
Thanks for the answer but it doesn't work.

I am totally new to it.

Is it possible to have a detailed tutorial?

**Comment by mplutka** [comment]
Please install everything mentioned here:
https://github.com/mplutka/tm-bt-led#prerequisites (Number 4)
In your case you are missing Git.

**Comment by mplutka** [comment]
You could also try to download the precompiled version:
https://github.com/mplutka/tm-bt-led/suites/2037117068/artifacts/40963445

If all goes well just follow the video in the documentation.

**Comment by mplutka** [comment]
Do you need any further help?

**Comment by Micke60** [comment]
Thanks for your help, I managed to get your software to work.

But by updating the Thrusmaster bluetooth, it removed the driver and I can no longer install it. Do you have a solution?

**Comment by Micke60** [comment]
![Led](https://user-images.githubusercontent.com/79248779/110547404-2b4fde80-8130-11eb-8096-60e20cf66c68.jpg)


Yes it is the bluetooth led update that crashed and since then I can not reinstall.
Yes I succeeded with Zadig for the Bluetooth usb key

**Comment by mplutka** [comment]
Oh, that doesn’t sound good.
Maybe Thrustmaster support can help.

**Comment by mplutka** [comment]
I‘m really sorry that this happened to your device. I‘m pretty sure that this had nothing to do with my software and occurred due to an hiccup during the firmware update process. So I’m closing this issue now. Wish you good luck with the TM support and would love to hear back from you if you managed to get it working again. Take care.

**Comment by mplutka** [comment]
Hi Micke60,
I think I found a way to revive your device.

Please follow these step precisely:
1. Turn OFF the TM BT Led
2. Fully charge the TM BT Led
3. UNPLUG the usb cable from the PC / charger
4. Launch the firmware update software on your PC
5. Turn ON the TM BT LED
6. HOLD the left top button (see screenshot)
![image](https://user-images.githubusercontent.com/5832625/111191153-0f2cc100-85b8-11eb-9a67-170fcf150213.png)
7. PLUG USB cable into PC
8. Firmware software should show this under "Device" (note the [BOOT] prefix before the entry):
![image](https://user-images.githubusercontent.com/5832625/111191283-32f00700-85b8-11eb-82f8-c09db757bd10.png)
9. RELEASE the left top button
10. Press OK on the firmware screen to start the update
11. Screen should look like this afterwards:
![image](https://user-images.githubusercontent.com/5832625/111191573-7f3b4700-85b8-11eb-9dbf-9ab1cfe8f3e4.png)

Please let me know if that worked for you.

**Comment by Micke60** [comment]
Thank you for your help, unfortunately despite the reset, the bluetooth does not work :(

I'll get the receipt to operate the warranty, I'll keep you posted;)
