### ISSUE TITLE
FH5

### ISSUE THREAD

**Issue by nazareth31** [mplutka/tm-bt-led#10]
Hi, i wonder if i can FH5.bat because, i try it on FH4 with the same thing but, i kept missing a step :/

**Comment by mplutka** [comment]
It already works with the current version 2.8.0:
https://github.com/mplutka/tm-bt-led/releases/download/2.8.0/2.8.0.zip

Enable "DATA OUT" in "HUD AND GAMEPLAY" settings, set IP address to 127.0.01 and port to 20127.
Use forza.bat to force forza mode.
