### ISSUE TITLE
F1 2021

### ISSUE THREAD

**Issue by Tony7719** [mplutka/tm-bt-led#12]
Hi does this work with f1 2021 as I can get it to sync with the display but it just a says F120** and can’t get anything to work with the display IE lap times

**Comment by mplutka** [comment]
Did you enable telemetry in the game and on the correct port? Should be 20777

**Comment by Tony7719** [comment]
I am not all that good with computers could you please explain how and plus would I need to do something with I racing as well to get the display to work many thanks

**Comment by Tony7719** [comment]
![image](https://user-images.githubusercontent.com/96962349/147863350-7abb83fb-b0e6-4bdf-84cc-3a42d8ac5028.jpg)
Please see photo

**Comment by mplutka** [comment]
Please turn OFF dbox, sli pro led and fanatec support and switch udp format from legacy to f1 2021. if this doesn’t work too please attach a screenshot of the command window where the Tm bt led App runs.

**Comment by Tony7719** [comment]
I’ve got f1 to work many thanks for that 
Just a quick question is there anything I need to do to get it to work with I racing I believe I have to run the game in 64bit is that correct 

thanks

**Comment by Tony7719** [comment]
![image](https://user-images.githubusercontent.com/96962349/147884222-b1a61946-0d1c-465b-bc24-0294f29eefdf.jpg)
