### ISSUE TITLE
I racing 

### ISSUE THREAD

**Issue by Tony7719** [mplutka/tm-bt-led#13]
Please see pictures as o can’t get it to work i.e lap times 
![Uploading 082EE344-8797-41C6-881C-A777D2EBBFF3.jpeg…]()

**Comment by Tony7719** [comment]
![Uploading DF178D2D-54C8-441E-A398-FF020FD111C3.jpeg…]()

**Comment by Tony7719** [comment]
![Uploading 3A99851F-D76A-4045-9EE8-4BB7C868C1D5.jpeg…]()

**Comment by mplutka** [comment]
Did you try the precompiled version linked in the readme? https://github.com/mplutka/tm-bt-led/releases/download/3.1.0/3.1.0.zip
