### ISSUE TITLE
DIY BT LED Display for Gran Turismo 7

### ISSUE THREAD

**Issue by aculedonaibaf** [mplutka/tm-bt-led#15]
Hi, I came across your project and wanted to ask you a question. I want to build my own LED display to use with Gran Turismo 7 but as far as I know GT7 does not provide telemetry....Somehow thrust master was able to get some basic data from the game and show in the led....Is there a simple way to connect GT7 with a raspberry to extract this data (RPM at least) so I can create my own gauge ? How did Thurstmaster get the telemetry from GT7 if it is not available....

**Comment by mplutka** [comment]
You are right. There seems to be no way to get telemetry from GT7, neither via UDP nor memory mapping which is supported by wild variety of games. So I guess TM must have access to some unofficial API.
