### ISSUE TITLE
Command prompt closing itself after couple minutes

### ISSUE THREAD

**Issue by Giulio0079** [mplutka/tm-bt-led#16]
Hi, first of all , as I said in one of my message while donating, thank you for the great work because it was surprisingly easy to get going in just a couple minutes.
Only issues I have (and probably something wrong on my end because I'm a bit of a noob ) is that the windows command prompt that runs the run.bat , close itself after a few minutes causing the bt led display to disconnect.
As I said , might be something wrong on my part. Any thoughts or suggestion? Thanks in advance anyway for this very cool tool

**Comment by calvintomaneng** [comment]
> Hi, first of all , as I said in one of my message while donating, thank you for the great work because it was surprisingly easy to get going in just a couple minutes. Only issues I have (and probably something wrong on my end because I'm a bit of a noob ) is that the windows command prompt that runs the run.bat , close itself after a few minutes causing the bt led display to disconnect. As I said , might be something wrong on my part. Any thoughts or suggestion? Thanks in advance anyway for this very cool tool

Hey there. I've been using this tool for a long time now because Markus has been very helpful since the beginning. I think I know what the issue is on your end. Previously the tool also crashes on me after using it for a few minutes due to some system instability (because of my PC specs, several USB and wireless connections, etc.) but Markus advised to try different refresh intervals to compensate for this issue.

For details instructions kindly read the "instability" section: https://github.com/mplutka/tm-bt-led#instability

Hope this helps! :)

**Comment by Giulio0079** [comment]
> > 
> 
> Hey there. I've been using this tool for a long time now because Markus has been very helpful since the beginning. I think I know what the issue is on your end. Previously the tool also crashes on me after using it for a few minutes due to some system instability (because of my PC specs, several USB and wireless connections, etc.) but Markus advised to try different refresh intervals to compensate for this issue.
> 
> For detailed instructions kindly read the "instability" section: https://github.com/mplutka/tm-bt-led#instability
> 
> Hope this helps! :)

Thank you very much , will try today with different intervals and/or a different port . btw my bad for missing the instability paragraph, was excited to have that work on the first try :) much appreciated

**Comment by Giulio0079** [comment]
Update : changing usb port and using the .exe file to launch the program (instead of running the run.bat file) solved my issue. Thank you very much again for your help
