### ISSUE TITLE
F1 2022

### ISSUE THREAD

**Issue by DoctorHub02** [mplutka/tm-bt-led#17]
Hi,
I managed to make F1 2022 runnung F1.js but after time it disconnect with no error.
I want to create dump file but don't know how.
May you help me?

**Comment by mplutka** [comment]
Hi,
try a longer interval e.g. by using run_compat.bat or adding --interval 50 (or higher) after the command.
Also run the script in a new cmd.exe window to see error messages on exit.

**Comment by DoctorHub02** [comment]
Ho, Thank you so much for the answer. I Will try and let you know of the
fix works.


Il ven 19 mag 2023, 08:27 Markus Plutka ***@***.***> ha
scritto:
