### ISSUE TITLE
plese help me create a game dump for grid legends 

### ISSUE THREAD

**Issue by cuttersworld** [mplutka/tm-bt-led#19]

**Comment by cuttersworld** [comment]
Thrustmaster bt display pc 
ps im using your software working nice have also sent donation
please help me

**Comment by mplutka** [comment]
And as GRID Legends seems to use the DiRT engine, support was added for this title in the current version 3.1.7.
Please refer to the DiRT Rally section in the readme for setup.

**Comment by cuttersworld** [comment]
HEY 
THANK YOU FOR V3.17 :)
I HAVE JUST TRIED IT BUT IT WONT CONNECT TO THE BT DISPLAY
 V3.16 WORKS FINE THOUGH

**Comment by cuttersworld** [comment]
UPDATE 
FIXED 
ALL WORKING 
GRID NOW WORKS 
I DIDNT INSTALL SETUP FIRST 
MY BAD
YOUR WORK TRUELY APPRECIATED 
MANY THANKS 
:)

**Comment by cuttersworld** [comment]
DIRT 3 NOW WORKING ALSO 
YOU LUCKY YOU NOT HERE 
I WOULD BE SWINGING AROUND YOU NECK TRYING TO KISS YOU LOOOOL
NO BUT SERIOUSLY 
MANY THANKS BRO 
COMMUNITY NEEDS MORE GUYS LIKE YOU
