### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by efexaa** [mplutka/tm-bt-led#2]
So i have downloaded the files you allready made to get going without installing etc...  
 but i get error this 
![Screenshot 2021-05-06 165133](https://user-images.githubusercontent.com/56225819/117328268-5e41f480-ae8b-11eb-9a8f-ee418e95b691.png)

**Comment by efexaa** [comment]
D:\Repos>setup
D:\Repos\node_modules\bluetooth-hci-socket\lib\usb.js:136
    this._aclDataInEndpoint.on('data', this.onAclDataInEndpointData.bind(this));
                            ^

TypeError: Cannot read property 'on' of undefined
    at BluetoothHciSocket.start (D:\Repos\node_modules\bluetooth-hci-socket\lib\usb.js:136:29)
    at Hci.init (D:\Repos\node_modules\noble\lib\hci-socket\hci.js:101:18)
    at NobleBindings.init (D:\Repos\node_modules\noble\lib\hci-socket\bindings.js:82:13)
    at D:\Repos\node_modules\noble\lib\noble.js:63:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by mplutka** [comment]
Can you check whether D:\tm-bt-led\node_modules\usb\build\Release\usb_bindings.node is there?
It should be otherwise the zip you downloaded wasn't complete or failed to extract everything.

I'm on node version 14.15.3. Maybe that could be a reason too, if you have another version.

**Comment by mplutka** [comment]
If all fails please try to install everything from scratch as described in the README. Make sure you install all of the required software beforehand.

**Comment by efexaa** [comment]
D:\Repos>setup
D:\Repos\node_modules\bluetooth-hci-socket\lib\usb.js:136
    this._aclDataInEndpoint.on('data', this.onAclDataInEndpointData.bind(this));
                            ^

TypeError: Cannot read property 'on' of undefined
    at BluetoothHciSocket.start (D:\Repos\node_modules\bluetooth-hci-socket\lib\usb.js:136:29)
    at Hci.init (D:\Repos\node_modules\noble\lib\hci-socket\hci.js:101:18)
    at NobleBindings.init (D:\Repos\node_modules\noble\lib\hci-socket\bindings.js:82:13)
    at D:\Repos\node_modules\noble\lib\noble.js:63:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
    
    What is that then?

**Comment by efexaa** [comment]
i had wrong version off Visual STudio and there was no C++ build.. so sorted that issue but now there is different thing 

D:\btled\node_modules\process-list\src\win\tasklist.cpp(17,10): fatal error C1083: Cannot open include file: 'atlbase.h
': No such file or directory [D:\btled\node_modules\process-list\build\processlist.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\btled\node_modules\process-list
gyp ERR! node -v v14.15.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! process-list@2.0.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the process-list@2.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by mplutka** [comment]
You are missing some depenencies. Maybe wrong version of visual studio or c++ development tools not installed. 

Also try this
![Uploading ECA9635F-7732-4190-97E7-5A13FE872AFC.png…]()

**Comment by mplutka** [comment]
![EFC507A8-0B11-4B95-A3A8-A9BF80BC2C4D](https://user-images.githubusercontent.com/5832625/117341237-2abe9480-aea2-11eb-8644-9c042431b918.png)

**Comment by efexaa** [comment]
Okey this helped now.. i installed... 

Still getting this

D:\tm-bt-led>setup
D:\tm-bt-led\node_modules\bluetooth-hci-socket\lib\usb.js:136
    this._aclDataInEndpoint.on('data', this.onAclDataInEndpointData.bind(this));
                            ^

TypeError: Cannot read property 'on' of undefined
    at BluetoothHciSocket.start (D:\tm-bt-led\node_modules\bluetooth-hci-socket\lib\usb.js:136:29)
    at Hci.init (D:\tm-bt-led\node_modules\noble\lib\hci-socket\hci.js:101:18)
    at NobleBindings.init (D:\tm-bt-led\node_modules\noble\lib\hci-socket\bindings.js:82:13)
    at D:\tm-bt-led\node_modules\noble\lib\noble.js:63:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by efexaa** [comment]
MY PC see Bluetooth adapter.. i bought the one you are using

**Comment by mplutka** [comment]
Never had this error before.  Which chipset does the stick have?

**Comment by efexaa** [comment]
![xxxx](https://user-images.githubusercontent.com/56225819/117352475-f4374880-aea6-11eb-8cd1-2c639f532758.png)
not too sure what you asking

**Comment by efexaa** [comment]
Driver version: 6.1.7600.16385

**Comment by mplutka** [comment]
Looks correct. Did you try to unplug the stick and plug it in again?

**Comment by efexaa** [comment]
Yes very strange.. it lets me to install it etc... but have no hope with setup lol and keep getting this 

D:\tm-bt-led-master>setup
D:\tm-bt-led-master\node_modules\bluetooth-hci-socket\lib\usb.js:136
    this._aclDataInEndpoint.on('data', this.onAclDataInEndpointData.bind(this));
                            ^

TypeError: Cannot read property 'on' of undefined
    at BluetoothHciSocket.start (D:\tm-bt-led-master\node_modules\bluetooth-hci-socket\lib\usb.js:136:29)
    at Hci.init (D:\tm-bt-led-master\node_modules\noble\lib\hci-socket\hci.js:101:18)
    at NobleBindings.init (D:\tm-bt-led-master\node_modules\noble\lib\hci-socket\bindings.js:82:13)
    at D:\tm-bt-led-master\node_modules\noble\lib\noble.js:63:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by mplutka** [comment]
It doesn’t find the usb stick. Can you try it in another port and if it is currently plugged into a hub maybe try a port directly at the pc

**Comment by efexaa** [comment]
i tried USB 2 USB3 i plugged at the front of PC.. it is working becouse its flashing blue... and PC can see it.. dont understand... what is try a port directly at the PC?

**Comment by mplutka** [comment]
The script can't initialize the stick. Try this:
Enter the following three lines in the cmd.exe prompt. Press enter after each one.
set BLUETOOTH_HCI_SOCKET_USB_VID=0x0a12
set BLUETOOTH_HCI_SOCKET_USB_PID=0x0001
setup.bat

**Comment by mplutka** [comment]
If this doesnt work, close the command prompt window and open another one with administrative rights
and try again

**Comment by efexaa** [comment]
im very sorry but its just crazy i cant do it... maybe not for me

C:\WINDOWS\system32>d:

D:\>cd tm-bt-led-master

D:\tm-bt-led-master>set BLUETOOTH_HCI_SOCKET_USB_VID=0x0a12

D:\tm-bt-led-master>set BLUETOOTH_HCI_SOCKET_USB_PID=0x0001

D:\tm-bt-led-master>setup.bat
D:\tm-bt-led-master\node_modules\bluetooth-hci-socket\lib\usb.js:136
    this._aclDataInEndpoint.on('data', this.onAclDataInEndpointData.bind(this));
                            ^

TypeError: Cannot read property 'on' of undefined
    at BluetoothHciSocket.start (D:\tm-bt-led-master\node_modules\bluetooth-hci-socket\lib\usb.js:136:29)
    at Hci.init (D:\tm-bt-led-master\node_modules\noble\lib\hci-socket\hci.js:101:18)
    at NobleBindings.init (D:\tm-bt-led-master\node_modules\noble\lib\hci-socket\bindings.js:82:13)
    at D:\tm-bt-led-master\node_modules\noble\lib\noble.js:63:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by mplutka** [comment]
Tried it with an admin cmd.exe?

**Comment by efexaa** [comment]
Yes

**Comment by efexaa** [comment]
It seems i have everything installed as it should..

**Comment by mplutka** [comment]
Yes, everything is installed correctly. It's the stick itself that is causing some issues.

Can you please open node_modules/bluetooth_hci_socket/lib/usb.js in a text editor.
Lines 96 - 101 should look like this. Can you verify?

![image](https://user-images.githubusercontent.com/5832625/117355881-644bcb80-aeb3-11eb-9a05-17128b8b54ac.png)

**Comment by efexaa** [comment]
Yes it seems all lines are fine

**Comment by mplutka** [comment]
Can you add this console.log line (103) and post the output here after running setup.bat?

![image](https://user-images.githubusercontent.com/5832625/117356572-2e5b1700-aeb4-11eb-8505-14b9ad020ec2.png)

**Comment by mplutka** [comment]
You should print out all the available endpoints for your adapter. I need the complete output. Thanks.

**Comment by efexaa** [comment]
InEndpoint {
    device: Device {
      busNumber: 2,
      deviceAddress: 15,
      deviceDescriptor: [Object],
      portNumbers: [Array],
      interfaces: [Array],
      _configDescriptor: [Object]
    },
    descriptor: {
      bLength: 7,
      bDescriptorType: 5,
      bEndpointAddress: 131,
      bmAttributes: 3,
      wMaxPacketSize: 16,
      bInterval: 1,
      bRefresh: 0,
      bSynchAddress: 0,
      extra: <Buffer >
    },
    address: 131,
    transferType: 3
  },
  OutEndpoint {
    device: Device {
      busNumber: 2,
      deviceAddress: 15,
      deviceDescriptor: [Object],
      portNumbers: [Array],
      interfaces: [Array],
      _configDescriptor: [Object]
    },
    descriptor: {
      bLength: 7,
      bDescriptorType: 5,
      bEndpointAddress: 1,
      bmAttributes: 2,
      wMaxPacketSize: 64,
      bInterval: 1,
      bRefresh: 0,
      bSynchAddress: 0,
      extra: <Buffer >
    },
    address: 1,
    transferType: 2
  },
  InEndpoint {
    device: Device {
      busNumber: 2,
      deviceAddress: 15,
      deviceDescriptor: [Object],
      portNumbers: [Array],
      interfaces: [Array],
      _configDescriptor: [Object]
    },
    descriptor: {
      bLength: 7,
      bDescriptorType: 5,
      bEndpointAddress: 129,
      bmAttributes: 2,
      wMaxPacketSize: 64,
      bInterval: 1,
      bRefresh: 0,
      bSynchAddress: 0,
      extra: <Buffer >
    },
    address: 129,
    transferType: 2
  }
]
D:\tm-bt-led\node_modules\bluetooth-hci-socket\lib\usb.js:136
    this._aclDataInEndpoint.on('data', this.onAclDataInEndpointData.bind(this));
                            ^

TypeError: Cannot read property 'on' of undefined
    at BluetoothHciSocket.start (D:\tm-bt-led\node_modules\bluetooth-hci-socket\lib\usb.js:136:29)
    at Hci.init (D:\tm-bt-led\node_modules\noble\lib\hci-socket\hci.js:101:18)
    at NobleBindings.init (D:\tm-bt-led\node_modules\noble\lib\hci-socket\bindings.js:82:13)
    at D:\tm-bt-led\node_modules\noble\lib\noble.js:63:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by mplutka** [comment]
We are getting there!
Try changing the line to this:
  this._aclDataOutEndpoint = this._usbDeviceInterface.endpoint(0x01);
  
  this._hciEventEndpoint = this._usbDeviceInterface.endpoint(0x83);
  this._aclDataInEndpoint = this._usbDeviceInterface.endpoint(0x81);

**Comment by mplutka** [comment]
You adapter seems to have other endpoint addresses. Indeed strange and the first time this occurred to me.

**Comment by efexaa** [comment]
InEndpoint {
    device: Device {
      busNumber: 2,
      deviceAddress: 15,
      deviceDescriptor: [Object],
      portNumbers: [Array],
      interfaces: [Array],
      _configDescriptor: [Object]
    },
    descriptor: {
      bLength: 7,
      bDescriptorType: 5,
      bEndpointAddress: 131,
      bmAttributes: 3,
      wMaxPacketSize: 16,
      bInterval: 1,
      bRefresh: 0,
      bSynchAddress: 0,
      extra: <Buffer >
    },
    address: 131,
    transferType: 3
  },
  OutEndpoint {
    device: Device {
      busNumber: 2,
      deviceAddress: 15,
      deviceDescriptor: [Object],
      portNumbers: [Array],
      interfaces: [Array],
      _configDescriptor: [Object]
    },
    descriptor: {
      bLength: 7,
      bDescriptorType: 5,
      bEndpointAddress: 1,
      bmAttributes: 2,
      wMaxPacketSize: 64,
      bInterval: 1,
      bRefresh: 0,
      bSynchAddress: 0,
      extra: <Buffer >
    },
    address: 1,
    transferType: 2
  },
  InEndpoint {
    device: Device {
      busNumber: 2,
      deviceAddress: 15,
      deviceDescriptor: [Object],
      portNumbers: [Array],
      interfaces: [Array],
      _configDescriptor: [Object]
    },
    descriptor: {
      bLength: 7,
      bDescriptorType: 5,
      bEndpointAddress: 129,
      bmAttributes: 2,
      wMaxPacketSize: 64,
      bInterval: 1,
      bRefresh: 0,
      bSynchAddress: 0,
      extra: <Buffer >
    },
    address: 129,
    transferType: 2
  }
]
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: LIBUSB_ERROR_NOT_FOUND
    at startTransfer (D:\tm-bt-led\node_modules\usb\usb.js:461:6)
    at Transfer.transferDone (D:\tm-bt-led\node_modules\usb\usb.js:448:4)
Emitted 'error' event on InEndpoint instance at:
    at startTransfer (D:\tm-bt-led\node_modules\usb\usb.js:463:9)
    at Transfer.transferDone (D:\tm-bt-led\node_modules\usb\usb.js:448:4) {
  errno: -5
}

**Comment by mplutka** [comment]
Ok, remove the console.log or comment it out like this
// console.log....
There is something interfering. Do you have another bluetooth adapter plugged in or some onboard bluetooth activated?
Maybe forcing it again with this might help:
set BLUETOOTH_HCI_SOCKET_USB_VID=0x0a12
set BLUETOOTH_HCI_SOCKET_USB_PID=0x0001
setup.bat

**Comment by efexaa** [comment]
Okey i did what you told me with three lines it came up as Starting scan but cant find anything

**Comment by mplutka** [comment]
Ok, that sounds good. Did you press both upper buttons of the bt led device while scanning?

**Comment by mplutka** [comment]
Did it also say "Discovering devices..."? If not, abort with Ctrl+C run setup.bat again

**Comment by efexaa** [comment]
:\tm-bt-led>setup.bat
1. Starting scan...

**Comment by efexaa** [comment]
Nothing more.
Yes i`m doing as instructed

**Comment by mplutka** [comment]
Can you add this instead the commented out console.log
console.log(this._usbDevice);

**Comment by efexaa** [comment]
D:\tm-bt-led>setup.bat
<ref *1> Device {
  busNumber: 1,
  deviceAddress: 3,
  deviceDescriptor: {
    bLength: 18,
    bDescriptorType: 1,
    bcdUSB: 512,
    bDeviceClass: 224,
    bDeviceSubClass: 1,
    bDeviceProtocol: 1,
    bMaxPacketSize0: 64,
    idVendor: 2578,
    idProduct: 1,
    bcdDevice: 9504,
    iManufacturer: 0,
    iProduct: 2,
    iSerialNumber: 0,
    bNumConfigurations: 1
  },
  portNumbers: [ 1 ],
  interfaces: [
    Interface {
      device: [Circular *1],
      id: 0,
      altSetting: 0,
      descriptor: [Object],
      interfaceNumber: 0,
      endpoints: [Array]
    },
    Interface {
      device: [Circular *1],
      id: 1,
      altSetting: 0,
      descriptor: [Object],
      interfaceNumber: 1,
      endpoints: [Array]
    }
  ],
  _configDescriptor: {
    bLength: 9,
    bDescriptorType: 2,
    wTotalLength: 177,
    bNumInterfaces: 2,
    bConfigurationValue: 1,
    iConfiguration: 0,
    bmAttributes: 160,
    bMaxPower: 50,
    extra: <Buffer >,
    interfaces: [ [Array], [Array] ]
  }
}
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: LIBUSB_ERROR_NOT_FOUND
    at startTransfer (D:\tm-bt-led\node_modules\usb\usb.js:461:6)
    at Transfer.transferDone (D:\tm-bt-led\node_modules\usb\usb.js:448:4)
Emitted 'error' event on InEndpoint instance at:
    at startTransfer (D:\tm-bt-led\node_modules\usb\usb.js:463:9)
    at Transfer.transferDone (D:\tm-bt-led\node_modules\usb\usb.js:448:4) {
  errno: -5
}

**Comment by mplutka** [comment]
Ok, change to this please 
console.log(this._usbDevice.interfaces[1].endpoints);

**Comment by mplutka** [comment]
Another try. Remove the console.log and change to this:
  this._usbDeviceInterface = this._usbDevice.interfaces[0];

  this._aclDataOutEndpoint = this._usbDeviceInterface.endpoint(0x02);

  this._hciEventEndpoint = this._usbDeviceInterface.endpoint(0x81);
  this._aclDataInEndpoint = this._usbDeviceInterface.endpoint(0x82);

**Comment by mplutka** [comment]
The bottom three lines are back to original state but the interface has changed to [1}

**Comment by efexaa** [comment]
OutEndpoint {
    device: Device {
      busNumber: 1,
      deviceAddress: 3,
      deviceDescriptor: [Object],
      portNumbers: [Array],
      interfaces: [Array],
      _configDescriptor: [Object]
    },
    descriptor: {
      bLength: 7,
      bDescriptorType: 5,
      bEndpointAddress: 2,
      bmAttributes: 1,
      wMaxPacketSize: 0,
      bInterval: 1,
      bRefresh: 0,
      bSynchAddress: 0,
      extra: <Buffer >
    },
    address: 2,
    transferType: 1
  },
  InEndpoint {
    device: Device {
      busNumber: 1,
      deviceAddress: 3,
      deviceDescriptor: [Object],
      portNumbers: [Array],
      interfaces: [Array],
      _configDescriptor: [Object]
    },
    descriptor: {
      bLength: 7,
      bDescriptorType: 5,
      bEndpointAddress: 130,
      bmAttributes: 1,
      wMaxPacketSize: 0,
      bInterval: 1,
      bRefresh: 0,
      bSynchAddress: 0,
      extra: <Buffer >
    },
    address: 130,
    transferType: 1
  }
]
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: LIBUSB_ERROR_NOT_FOUND
    at startTransfer (D:\tm-bt-led\node_modules\usb\usb.js:461:6)
    at Transfer.transferDone (D:\tm-bt-led\node_modules\usb\usb.js:448:4)
Emitted 'error' event on InEndpoint instance at:
    at startTransfer (D:\tm-bt-led\node_modules\usb\usb.js:463:9)
    at Transfer.transferDone (D:\tm-bt-led\node_modules\usb\usb.js:448:4) {
  errno: -5
}

D:\tm-bt-led>

D:\tm-bt-led>setup
D:\tm-bt-led\node_modules\bluetooth-hci-socket\lib\usb.js:103
  this._usbDevice.interfaces[1].endpoints();
                                ^

TypeError: this._usbDevice.interfaces[1].endpoints is not a function
    at BluetoothHciSocket.bindUser (D:\tm-bt-led\node_modules\bluetooth-hci-socket\lib\usb.js:103:33)
    at BluetoothHciSocket.bindRaw (D:\tm-bt-led\node_modules\bluetooth-hci-socket\lib\usb.js:47:8)
    at Hci.init (D:\tm-bt-led\node_modules\noble\lib\hci-socket\hci.js:100:35)
    at NobleBindings.init (D:\tm-bt-led\node_modules\noble\lib\hci-socket\bindings.js:82:13)
    at D:\tm-bt-led\node_modules\noble\lib\noble.js:63:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by mplutka** [comment]
CAn you show lines 96 - 105 please? There is something wrong there now

**Comment by efexaa** [comment]
this._usbDeviceInterface = this._usbDevice.interfaces[1];

  this._aclDataOutEndpoint = this._usbDeviceInterface.endpoint(0x02);

  this._hciEventEndpoint = this._usbDeviceInterface.endpoint(0x81);
  this._aclDataInEndpoint = this._usbDeviceInterface.endpoint(0x82);

  this._usbDevice.interfaces[1].endpoints();
};

**Comment by mplutka** [comment]
![image](https://user-images.githubusercontent.com/5832625/117360350-f99d8e80-aeb8-11eb-950f-152bc2dd739b.png)

**Comment by mplutka** [comment]
This is correct.

**Comment by mplutka** [comment]
Remove this._usbDevice.interfaces[1].endpoints();  and add
  this._usbDeviceInterface.claim();

**Comment by efexaa** [comment]
D:\tm-bt-led\node_modules\bluetooth-hci-socket\lib\usb.js:133
    this._hciEventEndpoint.on('data', this.onHciEventEndpointData.bind(this));
                           ^

TypeError: Cannot read property 'on' of undefined
    at BluetoothHciSocket.start (D:\tm-bt-led\node_modules\bluetooth-hci-socket\lib\usb.js:133:28)
    at Hci.init (D:\tm-bt-led\node_modules\noble\lib\hci-socket\hci.js:101:18)
    at NobleBindings.init (D:\tm-bt-led\node_modules\noble\lib\hci-socket\bindings.js:82:13)
    at D:\tm-bt-led\node_modules\noble\lib\noble.js:63:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by efexaa** [comment]
back to square one lol

**Comment by mplutka** [comment]
It seems your dongle model is incompatible, although it has the correct chipset. Maybe you can try another brand with this chipset or another compatible stick. 
Another guy had success with this one:
Realtek Bluetooth 8761B (USB VID: 0x0bda, USB PID: 0x8771, e.g. MPOW Bluetooth 5.0 stick)

I'm sorry, mate. Can't help you any further than this.... :-(

Also please change:
this._usbDeviceInterface = this._usbDevice.interfaces[1];
back to
this._usbDeviceInterface = this._usbDevice.interfaces[0];

**Comment by efexaa** [comment]
ye its sad.. it seems we got somewhere and then that happened

**Comment by mplutka** [comment]
Hope you can return it. The chipset is compatible but somehow the stick
isn’t

efexaa ***@***.***> schrieb am Do. 6. Mai 2021 um 22:29:

**Comment by mplutka** [comment]
I also heard of fake ones offered on eBay.
