### ISSUE TITLE
issue with Race Room Experience

### ISSUE THREAD

**Issue by SinisterY88** [mplutka/tm-bt-led#6]
Hi Markus, Shawn here. 
Got all games I have so far working with your program- thanks again except for race room experience. Brand new download. 
Attached is a copy/paste of text from the cmd prompt while the program is working showing the error.
[raceroom errors.txt](https://github.com/mplutka/tm-bt-led/files/6588690/raceroom.errors.txt)

As you can see the program found the BT LED and paired. Then the program successfully recognized that race room was run (along with displaying RACE ROOM on the BT LED display), but then a bunch of errors. 

Maybe you can take a look. Thanks.

**Comment by mplutka** [comment]
This was indeed a bug on my side. Thanks for the feedback.
Please try this release: https://github.com/mplutka/tm-bt-led/releases/download/2.7.2/2.7.2.zip

**Comment by SinisterY88** [comment]
Thanks for the  response. I am using 2.7.2 already and getting the errors as noted.

**Comment by mplutka** [comment]
This is a new build of 2.7.2 which should be ok
SinisterY88 ***@***.***> schrieb am Do. 3. Juni 2021 um 17:39:

**Comment by SinisterY88** [comment]
Hi Markus, an update in that it does seems to solve the issue- race room experience working ; )
