### ISSUE TITLE
Error executing setup.bat

### ISSUE THREAD

**Issue by ruuddenis** [mplutka/tm-bt-led#8]
Hi Markus,

Trying for a few weeks now to implement this, but no luck so far. Every time I get the following error while executing setup.bat: 

```
C:\Users\XXXXX\Documents\software\thrustmaster\bt-led\repo\node_modules\bluetooth-hci-socket\lib\usb.js:136
    this._aclDataInEndpoint.on('data', this.onAclDataInEndpointData.bind(this));
                            ^

TypeError: Cannot read property 'on' of undefined
    at BluetoothHciSocket.start (C:\Users\XXXXX\Documents\software\thrustmaster\bt-led\repo\node_modules\bluetooth-hci-socket\lib\usb.js:136:29)
    at Hci.init (C:\Users\XXXXX\Documents\software\thrustmaster\bt-led\repo\node_modules\noble\lib\hci-socket\hci.js:101:18)
    at NobleBindings.init (C:\Users\XXXXX\Documents\software\thrustmaster\bt-led\repo\node_modules\noble\lib\hci-socket\bindings.js:82:13)
    at C:\Users\XXXXX\Documents\software\thrustmaster\bt-led\repo\node_modules\noble\lib\noble.js:63:24
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
```

I'm using a CRS 4.0 (CSR8510 A10) bluetooth dongle, with WinUSB (v6.1.7600.16385) driver (also no luck with the other Zadig options), nodejs version 14.17.3 and npm version 6.14.13.

I followed all the steps listed in the readme and in the comments on Youtube....

Any idea what the issue is, and how to solve it? Your help is much appreciated, and certainly worthy of a donation. ;-)
*I also posted this under your Youtube video*

Thanks a lot,

Ruud

**Comment by mplutka** [comment]
Hi Ruud,

unfortunately I don’t have a solution for this. There is another closed issue like this here where it looked like that the usb stick was incompatible besides having a compatible chipset. The underlying Bluetooth software can’t initialise the stick. Do you have multiple Bluetooth adapters (maybe builtin) in your pc? If so disabling the other one might help. Otherwise maybe try another brand of stick.

**Comment by ruuddenis** [comment]
Markus,

You were right. The error was thrown because the usb bluetooth dongle was incompatible, despite having a compatible chip. It simply could not be initialized by the script...

Tried a dongle from my neighbour - *which had the same chip inside, but from a different brand* - and it worked. We had to change the interval to '50' in order to get it to work smoothly though.

Tested it yesterday evening, and only the 'delta' seems to be a bit wonky, as it seems to get stuck at +99.9 (and I'm not that slow 🤔)

Thanks for the support!

Ruud

**Comment by mplutka** [comment]
Hi Ruud,
Great to hear. This is why I had to put up so many disclaimers that I can‘t guarantee any success.
Are you trying Delta on F1? Then that’s my own implementation and could very well be buggy as i don’t get any data on that from the game. I try to calculate the delta in comparison to your best valid (!) lap valid of the current session. So it should show something useful after completing a complete lap without any track limit penalities etc 

Cheers
Markus

**Comment by ruuddenis** [comment]
Markus,

Totally understand the disclaimers. Read them before I purchased the BT-LED device, thought it would be worth giving it a shot. Great piece of work to make it work on a PC. 👊🏻

I'm currently only racing in Raceroom. Noticed the delta issue, and I suspect I saw a 'best lap' time from a deleted lap (track limits) too. 

Ruud

**Comment by mplutka** [comment]
Ok, then it’s data from the game. Will have a look at it but it can take a bit.

**Comment by ruuddenis** [comment]
Thanks Markus! Will be monitoring this repo closely... 😉
